#!/usr/bin/env bash
# Sets up a 404 page and a redirect page on a Nginx web server

# Install Nginx
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html


# Make error directory if it doesn't exist
if [[ ! -d /var/www/error ]]
then
    mkdir /var/www/error
fi

# Create custom 404 error file
echo "Ceci n'est pas une page" > /var/www/error/custom_404.html


# Add 404 file & redirect page info to default
STR="\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\
\n\terror_page 404 /custom_404.html;\
\n\tlocation = /custom_404.html {\
\n\t\troot /var/www/error;\
\n\t\tinternal;\
\n\t}\
\n\tadd_header X-Served-By \$hostname;\
\n}"

sed -i 's,^},'"$STR"',' /etc/nginx/sites-available/default

# Install HAProxy
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get install haproxy=1.8.\*



# Resart Web Server
service nginx restart
