#!/usr/bin/env bash
# install HAProxy and configure Load Balancer

# Install HAProxy
# apt-get -y install software-properties-common
# add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy

# Add Load Balancer configuration to haproxy.cfg
echo -e '
frontend http
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 1709-web-01 35.190.188.58:80 check
    server 1709-web-02 52.23.162.134:80 check' >> /etc/haproxy/haproxy.cfg

# Enable HAProxy
echo "ENABLED=1" >> /etc/default/haproxy

# Restart
service haproxy restart
