#!/usr/bin/env bash
# This is practice

hour="0"
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute="0"
    while [ $minute -le 59 ]
    do
        echo "$minute"
        ((minute=minute+1))
    done
    ((hour=hour+1))
done
