#!/usr/bin/env bash
# gives info about the holbertonschool file
FILE="holbertonschool"

if [ -e $FILE ]
then
    echo "$FILE file exists"
    # Check if file is empty
    if [ -s $FILE ]
    then
        echo "$FILE file is not empty"
    else
        echo "$FILE file is empty"
    fi
    # Check if file is a regular file
    if [ -f $FILE ]
    then
        echo "$FILE is a regular file"
    fi
else
    echo "$FILE file does not exist"
fi
