#!/usr/bin/env bash
# Changes home IP
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' ~/hosts.new
sudo echo "8.8.8.8 facebook.com" >> ~/hosts.new
sudo cp ~/hosts.new /etc/hosts
